---
title: "04_HeatMap"
output: html_notebook
---

What is the relationship among genes DE at different points in the time course?  Make a heat map!

```{r}
library(tidyverse)
library(gplots)
library(edgeR)
```

```{r}
load("../output/TimeCourseDGE_LRT.Rdata")
```

```{r}
names(models)
DEgenes <- models %>% 
  mutate(toptags = map(lrt, ~ topTags(.,n=Inf)), #pull the DE gene info out of each model
         toptags = map(toptags, ~ .$table), # get the table of DE info
         toptags = map(toptags, ~ rownames_to_column(., "transcript_ID"))) %>%
  unnest(toptags) %>%
  group_by(transcript_ID) %>%
  filter(min(FDR) < 0.05) # only keep genes where FDR < 0.05 in at least one comparison.
DEgenes %>% arrange(transcript_ID, FDR) %>% select(day_time, transcript_ID, logFC, FDR)
```

heat map of logFC

make a matrix from DEgenes
```{r}
DEgenes.mat.trunc <- DEgenes %>%
  select(day_time, transcript_ID, logFC) %>%
  mutate(logFC=ifelse(abs(logFC) > 4, sign(logFC)*4, logFC)) %>%
  spread(key = day_time, value = logFC) %>%
  as.data.frame() %>%
  column_to_rownames("transcript_ID") %>%
  as.matrix()
DEgenes.mat.trunc[1:10,1:10]
```

now, make the heat map

```{r, fig.height=10, fig.width=10}
DEgenes.mat.trunc %>% 
  heatmap.2(Colv = FALSE,
            keysize=1,
            dendrogram="row",
            sepwidth = c(0,0),
            labRow = FALSE,
            mar=c(12,0),
            srtCol = 45,
            col=colorRampPalette(c("green", "black", "magenta")),
            trace = "none",
            cexCol = 2
            #breaks=c(-8,-5, -2, -.5, .5, 2.5, 5, 10)
            )
            
```


count number of samples that each gene is DE in, and summarize

```{r}
DEgenes %>%
  summarize(n.timepoints=sum(FDR<0.05)) %>%
  group_by(n.timepoints) %>%
  summarize(n.genes=n()) %>%
  ggplot(aes(x=n.timepoints, y=n.genes)) +
  geom_col() +
  ggtitle("Number of genes detected at 1, 2, 3, ..., n time points") +
  ylab("number of genes") +
  xlab("number of time points")
```

Compare to previous experiment
```{r}
exp1 <- read_csv("../../Brapa_microbes/v3.0annotation/20170617-samples/output/FULLtoptag/root.trt5E_live.DEGs.add.rB.rFPsc.NB.v3.0anno.csv")
exp1
```

```{r}
sum(exp1$FDR<0.05)
```

Now go through each timepoint and compare with this list...

```{r}
exp1genes <- exp1$genes[exp1$FDR < 0.05]

overlap <- DEgenes %>% filter(FDR < 0.05) %>% 
  group_by(day_time) %>%
  summarize(total=n(), overlap=sum(transcript_ID %in% exp1genes), unique=total-overlap)
overlap
```

```{r}
overlap %>%
  select(-total) %>%
  gather(key="set", value="genes", -day_time) %>%
  ggplot(aes(x=day_time, y=genes, fill=set)) +
  geom_col() +
  theme(axis.text.x = element_text(angle=90, hjust = 1, vjust=0.5))
```

